[package]
name = "dbt"
version = "0.1.0"
authors = ["Gary Guo <gary@garyguo.net>"]
edition = "2018"

[workspace]
members = ["lib/softfp", "lib/p9", "lib/x86", "lib/riscv", "lib/fdt"]

[build-dependencies]
cc = "1.0"

[dependencies]
log = "0.4"
pretty_env_logger = "0.3"
libc = "0.2"
rand = "0.6"
fnv = "1.0"
fixedbitset = "0.1"
byteorder = "1.3"
lazy_static = "1.3"
spin = "0.5"
softfp = { path = "lib/softfp" }
p9 = { path = "lib/p9" }
x86 = { path = "lib/x86" }
riscv = { path = "lib/riscv" }
fdt = { path = "lib/fdt" }

[profile.dev]
opt-level = "z"
panic = "abort"

[profile.release]
panic = "abort"
debug = true

[features]
default = []
fast = []
thread = []
