[package]
name = "dbt"
version = "0.1.0"
authors = ["Gary Guo <gary@garyguo.net>"]
edition = "2018"

[workspace]
members = ["lib/softfp"]

[build-dependencies]
cc = "1.0"

[dependencies]
log = "0.4"
pretty_env_logger = "0.3"
libc = "0.2"
rand = "0.6"
fnv = "1.0"
num-traits = "0.2"
num-derive = "0.2"
fixedbitset = "0.1"
softfp = { path = "lib/softfp" }

[profile.dev]
opt-level = "z"
panic = "abort"

[profile.release]
panic = "abort"
debug = true
